### ISSUE TITLE
Can opencl install on Microsoft windows 8

### ISSUE THREAD

**Issue by ghost** [IFCA/opencl#38]
I try on cmd with "cabal install opencl".
But it failure. Input from command line show below.

https://docs.google.com/file/d/0B02yMjOZsqqFLWtRMzVtZU90dDQ/edit?usp=sharing

Sorry for my bad english.

**Comment by fegu** [comment]
Just to add to this for others finding it. My previous comment was for the Intel OpenCL SDK. For the latest (as of now, 3.0-beta) AMD OpenCL SDK (called AMD APP SDK) the paths on a 64bit machine are:
cabal install opencl --extra-include-dirs="c:\Program Files (x86)\AMD APP SDK\3.0-0-Beta\bin\x86_64" --extra-lib-dir
s="c:\Program Files (x86)\AMD APP SDK\3.0-0-Beta\lib\x86_64"

**Comment by fegu** [comment]
Just to add to this for others finding it. For the Intel Integrated Native Developer Experience (called Intel INDE) the paths on a 64bit machine are:
cabal install opencl --extra-include-dirs="C:\Intel\INDE\code_builder_5.1.0.25\include\CL" --extra-lib-dirs="C:\Intel\INDE\code_builder_5.1.0.25\lib\x64"
